/*
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/T-Systems-MMS/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */

import { ValidatorFn, Validators } from '@angular/forms';
import { BaseFormControlFactory } from 'openapi-typescript-angular-generator';



export interface Uni { 
    uniId: string;
    name?: string;
}

/**
 * Namespace for property- and property-value-enumerations of Uni.
 */
export namespace Uni {
    /**
     * All properties of Uni.
     */
    export enum Properties {
        uniId = 'uniId',
        name = 'name'
    }

    /**
    * A map of tuples with error name and `ValidatorFn` for each property of Uni.
    */
    export const ModelValidators: {[K in keyof Uni]: [string, ValidatorFn][]} = {
        uniId: [
                ['required', Validators.required],
                ['minlength', Validators.minLength(1)],
        ],
        name: [
        ],
    };

    /**
    * The FormControlFactory for Uni.
    */
    export class FormControlFactory extends BaseFormControlFactory<Uni> {

        /**
         * Constructor.
         *
         * @param model An existing model for Uni.
         *              If given, all form-controls of the factory automatically have the value of this model. If this
         *              model is not given, all values are `null`.
         */
        constructor(
          model: Uni = {
            uniId: null,
            name: null,
          }
        ) {
            super(model, Uni.ModelValidators);
        }
    }

}


