name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test action
        uses: colbyhill21/angular-full-ci/@v1.0
        with:
          testcommand: run test
